import 'job_model.dart';

final List<JobModel> dummyJobs = [
  JobModel(
    title: 'Security Escort for Actor - Airport to Residence',
    guardName: 'Hugo Jenkins • 5.0',
    location: 'Downtown Manhattan, NY',
    distance: '2.4 km away',
    time: '3h 20m left',
    price: '',
    status: 'In Progress',
    statusLabel: 'In Progress',
    showButton: true,
    buttonText: 'Check Out',
    rating: '',
  ),
  JobModel(
    title: 'Security Escort for Actor - Airport to Residence',
    guardName: 'Hugo Jenkins • 5.0',
    location: 'Downtown Manhattan, NY',
    distance: '2.4 km away',
    time: 'Starts in 28 min',
    price: '',
    status: 'Awaiting',
    statusLabel: 'Awaiting',
    showButton: true,
    buttonText: 'Check In',
    rating: '',
  ),
  JobModel(
    title: 'Security Escort for Actor - Airport to Residence',
    guardName: 'Hugo Jenkins • 5.0',
    location: 'Downtown Manhattan, NY',
    distance: '2.4 km away',
    time: '12:00 AM - 8:00 AM',
    price: '',
    status: 'Time',
    statusLabel: '12:45:00',
    showButton: false,
    rating: '',
  ),
  JobModel(
    title: 'Security Escort for Actor - Airport to Residence',
    guardName: 'Hugo Jenkins • 5.0',
    location: 'Downtown Manhattan, NY',
    distance: '2.4 km away',
    time: '9:00 AM - 5:00 PM',
    price: '',
    status: 'Pending',
    statusLabel: 'Pending',
    showButton: false,
    rating: '',
  ),
  JobModel(
    title: 'Security Escort for Actor - Airport to Residence',
    guardName: 'Hugo Jenkins • 5.0',
    location: 'Downtown Manhattan, NY',
    distance: '2.4 km away',
    time: '9:00 AM - 5:00 PM',
    price: '',
    status: 'Pending',
    statusLabel: 'Pending',
    showButton: false,
    rating: '',
  ),
  JobModel(
    title: 'Security Escort for Actor - Airport to Residence',
    guardName: 'Hugo Jenkins • 5.0',
    location: 'Downtown Manhattan, NY',
    distance: '2.4 km away',
    time: '9:00 AM - 5:00 PM',
    price: '',
    status: 'Pending',
    statusLabel: 'Pending',
    showButton: false,
    rating: '',
  ),
  JobModel(
    title: 'Security Escort for Actor - Airport to Residence',
    guardName: 'Hugo Jenkins • 5.0',
    location: '2644 Rosetta St, New Jersey, USA',
    distance: '2.4 km away',
    time: '9:00 AM - 5:00 PM',
    price: '\$4,598.00',
    status: 'Completed',
    statusLabel: 'Completed',
    showButton: true,
    buttonText: 'Share your review',
    rating: '',
  ),
  JobModel(
    title: 'Security Escort for Actor - Airport to Residence',
    guardName: 'Hugo Jenkins • 5.0',
    location: 'Downtown Manhattan, NY',
    distance: '2.4 km away',
    time: '9:00 AM - 6:00 PM',
    price: '',
    status: 'Cancelled',
    statusLabel: 'Cancelled',
    showButton: false,
    rating: '',
  ),
];
